apiVersion: apps/v1  
kind: Deployment
metadata:
  name: redis 
  namespace: demo-ops
  labels:
    app: counter       
spec:
  selector:
    matchLabels:     
      app: counter
  replicas: 1        
  template:  
    metadata:       
      labels:       
        app: counter
    spec:           
      containers:
      - name: redis
        image: redis:alpine
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 15
          periodSeconds: 20
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service        
metadata:
  name: redis
  labels:            
    app: counter
spec:
  ports:
  - port: 6379       
    targetPort: 6379
  selector:          
    app: counter