- hosts: all
  tasks:
    - name: Rename the hostname to demo-ops
      become: yes
      become_user: root
      hostname: 
        name: demo-ops
    - name: Create a user with name demo
      become: yes
      become_user: root
      user:
        name: demo
    - name: Add limits via sysctl 
      become: yes
      become_user: root
      sysctl:
        name: fs.file-max
        value: 65536
        sysctl_set: yes
        reload: yes
    - name: Add limits via sysctl 
      become: yes
      become_user: root
      sysctl:
        name: kernel.randomize_va_space
        value: 1
        sysctl_set: yes
        reload: yes
    - name: Set timezone to Asia/Kolkata
      become: yes
      become_user: root
      timezone:
        name: Asia/Kolkata
    - name: Install aptitude using apt
      become: yes
      become_user: root
      apt: 
        name: aptitude 
        state: latest 
        update_cache: yes 
        force_apt_get: yes
    - name: Add Docker GPG key
      become: yes
      become_user: root
      apt_key: 
        url: https://download.docker.com/linux/ubuntu/gpg
    - name: Add Docker APT repository
      become: yes
      become_user: root
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
    - name: Install list of packages
      become: yes
      become_user: root
      apt:
        name: ['apt-transport-https','ca-certificates','curl','software-properties-common','docker-ce']
        state: present
        update_cache: yes
    - name: Install Docker-compose
      become: yes
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.25.1/docker-compose-{{ansible_system}}-{{ansible_architecture}}"
        dest: /usr/local/bin/docker-compose
        mode: +x
    - name: Create code directory in the VM
      become: yes
      file:
        path: /etc/demo-ops
        state: directory
    - name: copy code into the VM
      become: yes
      shell: cp ./Dockerfile /etc/demo-ops/Dockerfile
    - name: copy code 
      become: yes
      shell: cp ./docker-compose.yaml /etc/demo-ops/docker-compose.yaml
    - name: Deploy the app
      become: yes
      shell: docker-compose up -d